change to a new way to solve `HookWebpackError ... Unclosed block`
The report when `pnpm build` is:

```bash
...
HookWebpackError: .../my-fuma/static/css/fb5ee875f83d1deb.css:2:58850: Unclosed block
```